[build]
command = "ng build --prod"
publish = "dist/rsbusinesstech-ui"

# commenting below 2 lines to disable scully as of now.
# command = "ng build --prod && npx scully"  
# publish = "dist/static" 

[build.environment]
NODE_VERSION = "16"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
